# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - uses: mxcl/xcodebuild@v3
      with:
        swift: 6.0
        action: none
    - run: xcodebuild test -scheme Coordinator -destination 'platform=iOS Simulator,OS:18.1,name:iPhone 16'
